version: '3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    networks:
      - monreseau
    restart: always

  admine:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - monreseau      
    links:
      - db

  python:
    build: .
    networks:
      - monreseau     
    depends_on:
      - db    
    links:
      - db

networks:
  monreseau:
     name: monreseau

